2022-04-13 20:44:24,685 INFO    MainThread:41264 [wandb_setup.py:_flush():75] Loading settings from C:\Users\10194\.config\wandb\settings
2022-04-13 20:44:24,685 INFO    MainThread:41264 [wandb_setup.py:_flush():75] Loading settings from d:\deep_learing_work\Spynet\wandb\settings
2022-04-13 20:44:24,685 INFO    MainThread:41264 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-13 20:44:24,685 INFO    MainThread:41264 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-13 20:44:24,686 INFO    MainThread:41264 [wandb_init.py:_log_setup():405] Logging user logs to d:\deep_learing_work\Spynet\wandb\run-20220413_204424-2egsxjvy\logs\debug.log
2022-04-13 20:44:24,687 INFO    MainThread:41264 [wandb_init.py:_log_setup():406] Logging internal logs to d:\deep_learing_work\Spynet\wandb\run-20220413_204424-2egsxjvy\logs\debug-internal.log
2022-04-13 20:44:24,687 INFO    MainThread:41264 [wandb_init.py:init():439] calling init triggers
2022-04-13 20:44:24,687 INFO    MainThread:41264 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-13 20:44:24,687 INFO    MainThread:41264 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3rg31wcq
2022-04-13 20:44:24,691 INFO    MainThread:41264 [wandb_run.py:finish():1539] finishing run wtj/spynet/3rg31wcq
2022-04-13 20:44:24,694 ERROR   MainThread:41264 [jupyter.py:save_history():421] Run pip install nbformat to save notebook history
2022-04-13 20:44:24,695 INFO    MainThread:41264 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-13 20:44:24,695 INFO    MainThread:41264 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-13 20:44:24,695 INFO    MainThread:41264 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-13 20:44:24,697 INFO    MainThread:41264 [wandb_run.py:_restore():1674] restore
2022-04-13 20:44:24,800 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 1151
}

2022-04-13 20:44:25,494 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 1151
}

2022-04-13 20:44:26,271 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3336
}

2022-04-13 20:44:26,382 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3363
}

2022-04-13 20:44:26,491 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3363
}

2022-04-13 20:44:26,605 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3363
}

2022-04-13 20:44:26,708 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3363
}

2022-04-13 20:44:26,815 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1151
  total_bytes: 3363
}

2022-04-13 20:44:26,925 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2951
  total_bytes: 3363
}

2022-04-13 20:44:27,035 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:27,137 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:27,240 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:27,349 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:27,458 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:27,569 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:28,666 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}

2022-04-13 20:44:29,655 INFO    MainThread:41264 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3363
  total_bytes: 3363
}
local_info {
}

2022-04-13 20:44:30,883 INFO    MainThread:41264 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-13 20:44:30,883 INFO    MainThread:41264 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-13 20:44:30,886 INFO    MainThread:41264 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-04-13 20:44:30,892 INFO    MainThread:41264 [wandb_init.py:init():492] starting backend
2022-04-13 20:44:30,893 INFO    MainThread:41264 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-04-13 20:44:30,900 INFO    MainThread:41264 [backend.py:ensure_launched():219] starting backend process...
2022-04-13 20:44:31,060 INFO    MainThread:41264 [backend.py:ensure_launched():224] started backend process with pid: 7644
2022-04-13 20:44:31,061 INFO    MainThread:41264 [wandb_init.py:init():501] backend started and connected
2022-04-13 20:44:31,073 INFO    MainThread:41264 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-13 20:44:31,073 INFO    MainThread:41264 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-13 20:44:31,073 INFO    MainThread:41264 [wandb_init.py:init():565] updated telemetry
2022-04-13 20:44:31,153 INFO    MainThread:41264 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-13 20:44:33,984 INFO    MainThread:41264 [wandb_run.py:_on_init():1759] communicating current version
2022-04-13 20:44:34,765 INFO    MainThread:41264 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-13 20:44:34,765 INFO    MainThread:41264 [wandb_init.py:init():625] starting run threads in backend
2022-04-13 20:44:35,062 INFO    MainThread:41264 [wandb_run.py:_console_start():1733] atexit reg
2022-04-13 20:44:35,063 INFO    MainThread:41264 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-13 20:44:35,064 INFO    MainThread:41264 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-13 20:44:35,066 INFO    MainThread:41264 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-13 20:44:35,067 INFO    MainThread:41264 [wandb_init.py:init():664] run started, returning control to user process
